name: Deploy Serverless App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./Terraform

      - name: Terraform Plan
        env:
          TF_VAR_budget_alert_email: ${{ secrets.BUDGET_ALERT_EMAIL }}
        run: terraform plan -input=false
        working-directory: ./Terraform

      - name: Terraform Apply
        env:
          TF_VAR_budget_alert_email: ${{ secrets.BUDGET_ALERT_EMAIL}}
        run: terraform apply -auto-approve
        working-directory: ./Terraform

      - name: Terraform Outputs
        run: terraform output -json
